name: Auto-Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into EC2 and Pull Latest Changes
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 18.222.76.244
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }} 
          port: 22
          script: |
            cd /var/www/CSC-648-848-S02-Spring2025-TEAM03
            git pull origin main
            exit
